[package]
name = "backup"
version = "0.0.3"
authors = ["Nicolas Embriz <nbari@tequila.io>"]
description = "create encrypted backups"
documentation = "https://github.com/nbari/backup"
homepage = "https://github.com/nbari/backup"
repository = "https://github.com/nbari/backup"
readme = "README.md"
keywords = ["backup", "cli", "restore"]
categories = ["command-line-interface", "command-line-utilities"]
license = "BSD-3-Clause"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "4", features = ["string", "env"] }
config = { version = "0.14", default-features = false, features = ["yaml"] }
dirs = "5"
openssl = { version = "0.10", optional = true, features = ["vendored"] }
rusqlite = { version = "0.32", features = ["bundled"] }
tempfile = "3.14"
walkdir = "2.5"
