---
name: Test & Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  coverage:
    uses: ./.github/workflows/coverage.yml
    secrets: inherit

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: test

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Branch name
        run: echo "${GITHUB_REF##*/}"

      - name: Get the release version from the tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux Dependencies
        run: sudo apt -y install musl-dev musl-tools
        if: matrix.os == 'ubuntu-latest'

      - name: Install Windows Dependencies
        run: |
          choco install openssl
        if: matrix.os == 'windows-latest'

      - name: Set OpenSSL Directory on Windows
        run: |
          echo 'OPENSSL_DIR=C:\Program Files\OpenSSL-Win64' >> $GITHUB_ENV
        if: matrix.os == 'windows-latest'

      - name: Build Project
        run: |-
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cargo build --release --locked --target ${{ matrix.target }} --features "openssl/vendored"
          else
            cargo build --release --locked --target ${{ matrix.target }}
          fi
