---
name: Coverage

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Run tests with coverage flags
        run: cargo test --verbose -- --nocapture
        env:
          RUST_BACKTRACE: full
          CARGO_INCREMENTAL: 0
          LLVM_PROFILE_FILE: coverage-%p-%m.profraw
          RUSTFLAGS: -Cinstrument-coverage -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off
          RUSTDOCFLAGS: -Cinstrument-coverage -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off

      - name: Install grcov
        run: |
          if [[ ! -x "$(command -v grcov)" ]]; then
            cargo install grcov
          fi

      - name: Generate coverage report
        run: |
          grcov . --binary-path target/debug/ \
                  -s . -t lcov --branch \
                  --ignore-not-existing \
                  --ignore '../**' --ignore '/*' \
                  -o coverage.lcov

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.lcov
          flags: rust
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.lcov
